# Install the World Cup 2026 dashboard to start at login on Windows.
# Creates a virtual environment, installs dependencies, and drops a hidden
# launcher in your Startup folder that runs the server with pythonw (no console
# window). Re-running is safe.
$ErrorActionPreference = "Stop"

# Repo root = two levels up from this script (scripts\windows\..\..)
$RepoDir = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
Write-Host "==> Repo: $RepoDir"

# 1. Virtual environment + dependencies
$Venv = Join-Path $RepoDir ".venv"
if (-not (Test-Path $Venv)) {
  Write-Host "==> Creating virtual environment"
  python -m venv $Venv
}
$VenvPy  = Join-Path $Venv "Scripts\python.exe"
$VenvPyw = Join-Path $Venv "Scripts\pythonw.exe"
& $VenvPy -m pip install --quiet --upgrade pip
& $VenvPy -m pip install --quiet -r (Join-Path $RepoDir "requirements.txt")
Write-Host "==> Dependencies installed"

# 2. .env scaffold (never overwrite an existing one)
$EnvFile = Join-Path $RepoDir ".env"
if (-not (Test-Path $EnvFile)) {
  Copy-Item (Join-Path $RepoDir ".env.example") $EnvFile
  Write-Host "==> Created .env (add a football-data.org key for faster live updates)"
}
New-Item -ItemType Directory -Force -Path (Join-Path $RepoDir "data\cache") | Out-Null

# 3. Write a hidden launcher straight into the Startup folder.
#    A .vbs lets us run pythonw with no console window and without blocking login.
$Startup  = [Environment]::GetFolderPath("Startup")
$Launcher = Join-Path $Startup "WorldCup2026Dashboard.vbs"
$vbs = @"
' Auto-generated by install-windows.ps1 — launches the dashboard hidden at login.
Set sh = CreateObject("WScript.Shell")
sh.CurrentDirectory = "$RepoDir"
sh.Run """$VenvPyw"" ""$RepoDir\run.py""", 0, False
"@
Set-Content -Path $Launcher -Value $vbs -Encoding ASCII
Write-Host "==> Startup launcher created: $Launcher"

# 4. Start it now (hidden)
Start-Process "wscript.exe" -ArgumentList "`"$Launcher`""
Write-Host "==> Dashboard starting…"

# 5. Friendly URL hint (reads PORT from .env if set)
$Port = 8765
$m = Select-String -Path $EnvFile -Pattern '^PORT=(.+)$' -ErrorAction SilentlyContinue
if ($m) { $Port = $m.Matches[0].Groups[1].Value }
Write-Host ""
Write-Host "Dashboard will be available at: http://127.0.0.1:$Port/"
Write-Host "Your browser should open shortly."
Write-Host "To stop it from running at login: scripts\windows\uninstall-windows.ps1"
